-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgoczgniQWbpuLen39
IGRHHkXhgM0uW76AkYLcoDIUjFqgCgYIKoZIzj0DAQehRANCAASusxiL3xgXQL4k
stEsDDDeE5p7vHN9pIqce8ZhXVYpZeqZC7pEdsdmJIq8MhM2KVXVxqDQ9JjQIDMq
cqKItHuQ
-----END PRIVATE KEY-----